name: set-ml
channels:
  - conda-forge
dependencies:
  - python=3.8.12
  - pip
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - ipython
  - jupyter
  - tensorboard
  - tqdm
  - pytorch
  - pip:
    - hydra-core
    - torch-tb-profiler
