paths:
  log: ${hydra:runtime.cwd}/../log
  checkpoints: ${hydra:runtime.cwd}/../checkpoints
  results: ${hydra:runtime.cwd}/../results

experiment:
  max_epochs: 500
  patience: 15
  min_delta: 1e-9
  lr: 0.001
  batch_size: 64
  random_seed: 99
  weight_decay: 5e-3
  grad_norm_threshold: 10.0
  use_batch_sampler: False
  use_gpu: False
  results_out: results.csv

model:
  type: deepsets_mlp_sum
  data_dim: 1
  laten_dim: 8

task:
  max_set_size: 8
  min_value: -100
  max_value: 100
  label: sum
  multisets: True

datasets:
  train_samples: 10000
  valid_samples: 1000
  test_samples: 1000