paths:
  log: ${hydra:runtime.cwd}/log
 # data: ./dataset
  results: ${hydra:runtime.cwd}/results/results.csv

experiment:
  epochs: 1
  lr: 5e-5
  batch_size: 128
  random_seed: 99
  loss: mse
  weight_decay: 5e-3

model:
  accumulator: max
  laten_dim: 10

trainset:
  n_samples: 10
  max_set_size: 10
  min_value: 0
  max_value: 10
  label: max # Independent of accumulator
  multisets: True 

validset:
  n_samples: 10
  max_set_size: 10
  min_value: 0
  max_value: 10
  label: max # Independent of accumulator
  multisets: True 

testset:
  n_samples: 10
  max_set_size: 10
  min_value: 0
  max_value: 10
  label: max # Independent of accumulator
  multisets: True 
#   n_samples: 100
