paths:
  log: ${hydra:runtime.cwd}/log
 # data: ./dataset
  models: ${hydra:runtime.cwd}/models
  results: ${hydra:runtime.cwd}/results/results.csv

experiment:
  max_epochs: 200
  early_stopping_patience: 5
  lr: 0.001
  batch_size: 64
  random_seed: 99
  loss: mse
  weight_decay: 5e-3

model:
  type: deepsets_mlp
  data_dim: 1
  laten_dim: 10
  accumulator: sum

set_vals:
  max_set_size: 10
  min_value: 0
  max_value: 10
  label: max # Independent of accumulator
  multisets: True

trainset:
  n_samples: 10000

validset:
  n_samples: 1000

testset:
  n_samples: 1000
