paths:
  log: ${hydra:runtime.cwd}/log
  models: ${hydra:runtime.cwd}/models
  results: ${hydra:runtime.cwd}/results

experiment:
  max_epochs: 500
  patience: 15
  min_delta: 1e-9
  lr: 0.001
  batch_size: 64
  random_seed: 99
  weight_decay: 5e-3
  grad_norm_threshold: 50.0
  use_batch_sampler: False
  use_gpu: False

model:
  type: deepsets_mlp_sum
  data_dim: 1
  laten_dim: 10

task:
  max_set_size: 10
  min_value: 0
  max_value: 10
  label: sum
  multisets: True

datasets:
  train_samples: 10000
  valid_samples: 1000
  test_samples: 1000